"""Generated by MLBlock."""

import requests
import os

BACKEND_URL = os.environ.get('BACKEND_URL', 'http://localhost:8000')
GPU_API_KEY = os.environ.get('GPU_API_KEY', 'mock-gpu-key')
JOB_ID = os.environ.get('JOB_ID', 'mock-job-id')

def notify_status(block, status):
    try:
        requests.post(f'{BACKEND_URL}/jobs/{JOB_ID}/status',
            json={'block': block, 'status': status},
            headers={'Authorization': f'Bearer {GPU_API_KEY}'}, timeout=5)
    except Exception: pass

def notify_output(block, output):
    try:
        requests.post(f'{BACKEND_URL}/jobs/{JOB_ID}/output',
            json={'block': block, 'output': str(output)[:10000]},
            headers={'Authorization': f'Bearer {GPU_API_KEY}'}, timeout=5)
    except Exception: pass

def notify_error(block, error):
    try:
        requests.post(f'{BACKEND_URL}/jobs/{JOB_ID}/error',
            json={'block': block, 'error': str(error)},
            headers={'Authorization': f'Bearer {GPU_API_KEY}'}, timeout=5)
    except Exception: pass

# === input ===
import torch
from torch import nn


def input(shape: "list[int]") -> "torch.Tensor":
    """Input.
    
    Args:
        shape: Parameter.
    """
    return nn.Input(shape=shape)(x)

# === conv2d ===
import torch
from torch import nn


def conv2d(x: "torch.Tensor", in_channels: "int", out_channels: "int", kernel_size: "int" = 3, stride: "int" = 1, padding: "int" = 0) -> "torch.Tensor":
    """Conv2D.
    
    Args:
        x: Input tensor.
        in_channels: Parameter.
        out_channels: Parameter.
        kernel_size: Parameter.
        stride: Parameter.
        padding: Parameter.
    """
    return nn.Conv2d(in_channels=in_channels, out_channels=out_channels, kernel_size=kernel_size, stride=stride, padding=padding)(x)

# === relu ===
import torch
from torch import nn


def relu(x: "torch.Tensor") -> "torch.Tensor":
    """ReLU.
    
    Args:
        x: Input tensor.
    """
    return nn.ReLU()(x)

# === maxpool2d ===
import torch
from torch import nn


def maxpool2d(x: "torch.Tensor", kernel_size: "int" = 2, stride: "int" = None) -> "torch.Tensor":
    """MaxPool2D.
    
    Args:
        x: Input tensor.
        kernel_size: Parameter.
        stride: Parameter.
    """
    return nn.MaxPool2d(kernel_size=kernel_size, stride=stride)(x)

# === flatten ===
import torch
from torch import nn


def flatten(x: "torch.Tensor") -> "torch.Tensor":
    """Flatten.
    
    Args:
        x: Input tensor.
    """
    return nn.Flatten()(x)

# === linear ===
import torch
from torch import nn


def linear(x: "torch.Tensor", in_features: "int", out_features: "int", bias: "bool" = True) -> "torch.Tensor":
    """Linear (FC).
    
    Args:
        x: Input tensor.
        in_features: Parameter.
        out_features: Parameter.
        bias: Parameter.
    """
    return nn.Linear(in_features=in_features, out_features=out_features, bias=bias)(x)

# === softmax ===
import torch
from torch import nn


def softmax(x: "torch.Tensor", dim: "int" = 1) -> "torch.Tensor":
    """Softmax.
    
    Args:
        x: Input tensor.
        dim: Parameter.
    """
    return nn.Softmax(dim=dim)(x)

def main():
    try:
        notify_status('input', 'running')
        out_input_1 = input(shape=[1, 28, 28])
        notify_output('input', out_input_1)
        notify_status('input', 'done')
        notify_status('conv2d', 'running')
        out_conv1 = conv2d(x=out_input_1, in_channels=1, out_channels=32, kernel_size=3)
        notify_output('conv2d', out_conv1)
        notify_status('conv2d', 'done')
        notify_status('relu', 'running')
        out_relu1 = relu(x=out_conv1)
        notify_output('relu', out_relu1)
        notify_status('relu', 'done')
        notify_status('maxpool2d', 'running')
        out_pool1 = maxpool2d(x=out_relu1, kernel_size=2)
        notify_output('maxpool2d', out_pool1)
        notify_status('maxpool2d', 'done')
        notify_status('conv2d', 'running')
        out_conv2 = conv2d(x=out_pool1, in_channels=32, out_channels=64, kernel_size=3)
        notify_output('conv2d', out_conv2)
        notify_status('conv2d', 'done')
        notify_status('relu', 'running')
        out_relu2 = relu(x=out_conv2)
        notify_output('relu', out_relu2)
        notify_status('relu', 'done')
        notify_status('maxpool2d', 'running')
        out_pool2 = maxpool2d(x=out_relu2, kernel_size=2)
        notify_output('maxpool2d', out_pool2)
        notify_status('maxpool2d', 'done')
        notify_status('flatten', 'running')
        out_flat = flatten(x=out_pool2)
        notify_output('flatten', out_flat)
        notify_status('flatten', 'done')
        notify_status('linear', 'running')
        out_fc1 = linear(x=out_flat, in_features=1600, out_features=128)
        notify_output('linear', out_fc1)
        notify_status('linear', 'done')
        notify_status('relu', 'running')
        out_relu3 = relu(x=out_fc1)
        notify_output('relu', out_relu3)
        notify_status('relu', 'done')
        notify_status('linear', 'running')
        out_fc2 = linear(x=out_relu3, in_features=128, out_features=10)
        notify_output('linear', out_fc2)
        notify_status('linear', 'done')
        notify_status('softmax', 'running')
        out_output = softmax(x=out_fc2, dim=1)
        notify_output('softmax', out_output)
        notify_status('softmax', 'done')
        notify_status('pipeline', 'done')
    except Exception as e:
        notify_error('pipeline', e)
        raise

if __name__ == "__main__":
    main()