"""
Generated by MLBlock
"""

import torch.nn as nn


def main():
    conv1_out = nn.Conv2d(1, 32, kernel_size=3, stride=1, padding=0)
    relu1_out = nn.ReLU()
    pool1_out = nn.MaxPool2d(kernel_size=2)
    conv2_out = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=0)
    relu2_out = nn.ReLU()
    pool2_out = nn.MaxPool2d(kernel_size=2)
    flat_out = nn.Flatten()
    fc1_out = nn.Linear(1600, 128, bias=True)
    relu3_out = nn.ReLU()
    fc2_out = nn.Linear(128, 10, bias=True)
    output_out = nn.Softmax(dim=1)

if __name__ == "__main__":
    main()

