from mlblock.server.schemas import PipelineNode, PipelineEdge


TRUNCATE_AT = 20000  # single owner for truncation (was duplicated 3×)

# Canonical serialize shape — single owner (was duplicated in generator string + InspectorPanel)
def _serialize_value(v: object) -> dict:
    """Python-side helper for tests — mirrors the string-emitted _serialize_output."""
    import base64

    def is_nums(x: object) -> bool:
        return isinstance(x, (list, tuple)) and len(x) > 0 and all(
            isinstance(i, (int, float)) and not isinstance(i, bool) for i in x  # type: ignore
        )

    if isinstance(v, bytes):
        return {"type": "image", "mime": "image/png", "data": base64.b64encode(v).decode("ascii")}
    if is_nums(v):
        return {"type": "curve", "points": [float(x) for x in v]}  # type: ignore
    if isinstance(v, dict):
        h = v.get("history")  # type: ignore
        if is_nums(h):
            return {"type": "curve", "points": [float(x) for x in h]}  # type: ignore
        scalars = {k: x for k, x in v.items() if isinstance(x, (int, float, str, bool))}  # type: ignore
        if scalars:
            return {
                "type": "metrics",
                "values": {k: (float(x) if isinstance(x, (int, float)) else x) for k, x in scalars.items()},
            }
    if isinstance(v, (int, float)) and not isinstance(v, bool):
        return {"type": "metric", "value": float(v)}
    return {"type": "text", "text": str(v)}


def _topological_sort(nodes: list[PipelineNode], edges: list[PipelineEdge]) -> list[str]:
    # Delegate to Validation's single deque implementation (one topo, not two)
    from mlblock.validation import _topological_sort as _val_topo

    # Validation topo works on dicts — adapt
    node_dicts = [{"id": n.id} for n in nodes]
    edge_dicts = [{"source": e.source, "target": e.target} for e in edges]
    order, _ = _val_topo(node_dicts, edge_dicts)
    return order


def _source_for(block_name: str) -> str:
    try:
        from mlblock.catalog import catalog

        return catalog.get_source(block_name)
    except Exception:
        from mlblock.blocks.registry import BLOCK_SOURCES

        return BLOCK_SOURCES.get(block_name, "")


def generate_code(nodes: list[PipelineNode], edges: list[PipelineEdge]) -> str:
    from mlblock.blocks.registry import BLOCK_REGISTRY
    lines = ['"""Generated by MLBlock."""', ""]

    lines.append("import requests")
    lines.append("import os")
    lines.append("import json")
    lines.append("")
    lines.append("BACKEND_URL = os.environ.get('BACKEND_URL', 'http://localhost:8000')")
    # gpu-instance-auth : sur une instance Vast, Vast injecte CONTAINER_API_KEY
    # (clé restreinte de l'instance) — elle authentifie les callbacks de ce job.
    # En local (subprocess) seul GPU_API_KEY existe (mock par défaut).
    lines.append("GPU_API_KEY = os.environ.get('GPU_API_KEY') or os.environ.get('CONTAINER_API_KEY', 'mock-gpu-key')")
    lines.append("JOB_ID = os.environ.get('JOB_ID', 'mock-job-id')")
    lines.append("")
    # ponytail: 90s timeout — Render free tier spins down after 15min idle,
    # takes ~60s to wake up on first HTTP request. GPU callbacks must wait
    # for the backend to spin back up before the request can succeed.
    lines.append("BACKEND_TIMEOUT = int(os.environ.get('BACKEND_TIMEOUT', '90'))")
    lines.append("def notify_status(block, status, block_id=None):")
    lines.append("    try:")
    lines.append("        payload = {'block': block, 'status': status}")
    lines.append("        if block_id is not None:")
    lines.append("            payload['block_id'] = block_id")
    lines.append("        requests.post(f'{BACKEND_URL}/api/jobs/{JOB_ID}/status',")
    lines.append("            json=payload,")
    lines.append("            headers={'Authorization': f'Bearer {GPU_API_KEY}'}, timeout=BACKEND_TIMEOUT)")
    lines.append("    except Exception: pass")
    lines.append("")
    lines.append("def notify_output(block, output, block_id=None):")
    lines.append("    try:")
    lines.append("        if len(str(output)) > 20000:")
    lines.append("            output = str(output)[:20000] + '...[truncated]'")
    lines.append("        payload = {'block': block, 'output': str(output)}")
    lines.append("        if block_id is not None:")
    lines.append("            payload['block_id'] = block_id")
    lines.append("        else:")
    lines.append("            try:")
    lines.append("                _d = json.loads(str(output))")
    lines.append("                if isinstance(_d, dict) and 'block_id' in _d:")
    lines.append("                    payload['block_id'] = _d['block_id']")
    lines.append("            except Exception: pass")
    lines.append("        requests.post(f'{BACKEND_URL}/api/jobs/{JOB_ID}/output',")
    lines.append("            json=payload,")
    lines.append("            headers={'Authorization': f'Bearer {GPU_API_KEY}'}, timeout=BACKEND_TIMEOUT)")
    lines.append("    except Exception: pass")
    lines.append("")
    lines.append("def _serialize_output(v):")
    lines.append("    import base64")
    lines.append("    import json")
    lines.append("    def is_nums(x):")
    lines.append(
        "        return isinstance(x, (list, tuple)) and len(x) > 0 and all(isinstance(i, (int, float)) "
        "and not isinstance(i, bool) for i in x)"
    )
    lines.append("    if isinstance(v, bytes):")
    lines.append("        return {'type': 'image', 'mime': 'image/png', 'data': base64.b64encode(v).decode('ascii')}")
    lines.append("    if is_nums(v):")
    lines.append("        return {'type': 'curve', 'points': [float(x) for x in v]}")
    lines.append("    if isinstance(v, dict):")
    lines.append("        h = v.get('history')")
    lines.append("        if is_nums(h):")
    lines.append("            return {'type': 'curve', 'points': [float(x) for x in h]}")
    lines.append("        scalars = {k: x for k, x in v.items() if isinstance(x, (int, float, str, bool))}")
    lines.append("        if scalars:")
    lines.append(
        "            return {'type': 'metrics', 'values': {k: (float(x) if isinstance(x, (int, float)) "
        "else x) for k, x in scalars.items()}}"
    )
    lines.append("    if isinstance(v, (int, float)) and not isinstance(v, bool):")
    lines.append("        return {'type': 'metric', 'value': float(v)}")
    lines.append("    return {'type': 'text', 'text': str(v)}")
    lines.append("")
    lines.append("def notify_error(block, error):")
    lines.append("    try:")
    lines.append("        requests.post(f'{BACKEND_URL}/api/jobs/{JOB_ID}/error',")
    lines.append("            json={'block': block, 'error': str(error)},")
    lines.append("            headers={'Authorization': f'Bearer {GPU_API_KEY}'}, timeout=BACKEND_TIMEOUT)")
    lines.append("    except Exception: pass")
    lines.append("")
    lines.append("INSTANCE_ID = None")
    lines.append("")
    lines.append("def _fetch_instance_id():")
    lines.append("    \"\"\"GPU uniquement : id Vast de cette instance, via le backend.\"\"\"")
    lines.append("    global INSTANCE_ID")
    lines.append("    if not os.environ.get('CONTAINER_API_KEY'):")
    lines.append("        return")
    lines.append("    try:")
    lines.append("        r = requests.get(f'{BACKEND_URL}/api/jobs/{JOB_ID}/instance',")
    lines.append("            headers={'Authorization': f'Bearer {GPU_API_KEY}'}, timeout=BACKEND_TIMEOUT)")
    lines.append("        INSTANCE_ID = r.json().get('instance_id')")
    lines.append("    except Exception: pass")
    lines.append("")
    lines.append("def _self_destroy():")
    lines.append("    \"\"\"GPU uniquement : détruit l'instance en fin de run (filet anti-orpheline).\"\"\"")
    lines.append("    key = os.environ.get('CONTAINER_API_KEY')")
    lines.append("    if not key or not INSTANCE_ID:")
    lines.append("        return")
    lines.append("    try:")
    lines.append("        requests.delete(f'https://console.vast.ai/api/v0/instances/{INSTANCE_ID}',")
    lines.append("            headers={'Authorization': f'Bearer {key}'}, timeout=10)")
    lines.append("    except Exception: pass")
    lines.append("")

    seen = set()
    for node in nodes:
        if node.type in seen:
            continue
        seen.add(node.type)
        source = _source_for(node.type)
        if source:
            lines.append(f"# === {node.type} ===")
            lines.append(source.strip())
            lines.append("")

    lines.append("def main():")
    lines.append("    _fetch_instance_id()")
    lines.append("    try:")

    order = _topological_sort(nodes, edges)
    if len(order) != len(nodes):
        raise ValueError("Cycle detected in pipeline graph")

    output_counter = 0
    output_map: dict = {}

    for node_id in order:
        node = next(n for n in nodes if n.id == node_id)
        block = BLOCK_REGISTRY.get(node.type)
        if not block:
            continue

        cleaned_params = {k: v for k, v in node.params.items() if not k.startswith("_")}
        # Coerce les strings frontend vers les types Python déclarés (même
        # logique que le build) — sinon le code généré planterait sur
        # ratio='0.8', shuffle='true', etc.
        from mlblock.core.block import _coerce_param_value

        emitted: list[str] = []
        for k, v in cleaned_params.items():
            pinfo = block.params.get(k) if block else None
            ptype = pinfo.type if pinfo is not None else None
            if ptype:
                v = _coerce_param_value(block.name, k, v, ptype)
            emitted.append(f"{k}={v!r}")
        params = ", ".join(emitted)

        PORT_TO_PARAM = {"in": "in_1", "input": "in_1", "x": "in_1", "in_1": "in_1"}

        resolved_inputs = []
        for edge in edges:
            if edge.target == node_id:
                key = (edge.source, edge.source_port)
                if key in output_map:
                    var_name = f"out_{output_map[key]}"
                elif edge.source in output_map:
                    var_name = f"out_{output_map[edge.source]}"
                else:
                    var_name = f"out_{edge.source}"
                target_param = PORT_TO_PARAM.get(edge.target_port, edge.target_port)
                resolved_inputs.append(f"{target_param}={var_name}")
        inputs = ", ".join(resolved_inputs)

        args = ", ".join(filter(None, [inputs, params]))
        # block_id = node.id for per-block Inspecteur mapping (type for display, id for mapping)
        bid = repr(node.id)
        lines.append(f"        notify_status({node.type!r}, 'running', {bid})")
        if len(block.outputs) <= 1:
            output_counter += 1
            output_map[node_id] = output_counter
            lines.append(f"        out_{output_counter} = {node.type}({args})")
            lines.append(f"        notify_output({node.type!r}, json.dumps(_serialize_output(out_{output_counter})), {bid})")  # noqa: E501
        else:
            targets = []
            for o in block.outputs:
                output_counter += 1
                output_map[(node_id, o['name'])] = output_counter
                targets.append(f"out_{output_counter}")
            lines.append(f"        {', '.join(targets)} = {node.type}({args})")
            for t in targets:
                lines.append(f"        notify_output({node.type!r}, json.dumps(_serialize_output({t})), {bid})")
        lines.append(f"        notify_status({node.type!r}, 'done', {bid})")
    lines.append("        notify_status('pipeline', 'done')")
    lines.append("    except Exception as e:")
    lines.append("        notify_error('pipeline', e)")
    lines.append("        raise")
    lines.append("    finally:")
    lines.append("        _self_destroy()")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    main()")
    return "\n".join(lines)


def generate_with_ir(nodes: list[PipelineNode], edges: list[PipelineEdge]) -> dict:
    """Deep Codegen: returns {code, ir} — interface is the test surface (IR, not string)."""
    code = generate_code(nodes, edges)
    order = _topological_sort(nodes, edges)
    # Build minimal IR: order + outputMap + perNode
    from mlblock.catalog import catalog

    output_counter = 0
    output_map: dict = {}
    per_node = []
    for nid in order:
        n = next((x for x in nodes if x.id == nid), None)
        if not n:
            continue
        block = catalog.get(n.type)
        if not block:
            continue
        if len(block.outputs) <= 1:
            output_counter += 1
            output_map[nid] = output_counter
            per_node.append({"id": nid, "type": n.type, "out": f"out_{output_counter}"})
        else:
            for o in block.outputs:
                output_counter += 1
                output_map[(nid, o["name"])] = output_counter  # type: ignore
            per_node.append({"id": nid, "type": n.type, "outs": list(output_map.values())[-len(block.outputs):]})
    return {
        "code": code,
        "ir": {"order": order, "outputMap": output_map, "perNode": per_node, "truncateAt": TRUNCATE_AT},
    }


class CodeGenerator:
    """Deprecated shim — kept for pipeline.py compatibility until total deletion. Use generate_code/generate_with_ir."""

    def __init__(self, graph):
        self.graph = graph

    def generate(self) -> str:
        nodes = []
        for n in self.graph.nodes.values():
            nodes.append(PipelineNode(id=n.id, type=n.type, params=n.params))

        edges = []
        for e in self.graph.edges:
            edges.append(PipelineEdge(
                source=e.source,
                source_port=e.source_port,
                target=e.target,
                target_port=e.target_port
            ))

        return generate_code(nodes, edges)
