from typing import Any
from mlblock.server.schemas import PipelineNode, PipelineEdge


def _topological_sort(nodes: list[PipelineNode], edges: list[PipelineEdge]) -> list[str]:
    graph: dict[str, list[str]] = {n.id: [] for n in nodes}
    in_degree: dict[str, int] = {n.id: 0 for n in nodes}
    for edge in edges:
        graph.setdefault(edge.source, []).append(edge.target)
        in_degree[edge.target] = in_degree.get(edge.target, 0) + 1
    queue = [nid for nid, deg in in_degree.items() if deg == 0]
    order = []
    while queue:
        nid = queue.pop(0)
        order.append(nid)
        for t in graph.get(nid, []):
            in_degree[t] -= 1
            if in_degree[t] == 0:
                queue.append(t)
    return order


def _source_for(block_name: str) -> str:
    from mlblock.blocks.registry import BLOCK_SOURCES
    return BLOCK_SOURCES.get(block_name, "")


def generate_code(nodes: list[PipelineNode], edges: list[PipelineEdge]) -> str:
    from mlblock.blocks.registry import BLOCK_REGISTRY, BLOCK_SOURCES
    lines = ['"""Generated by MLBlock."""', ""]

    lines.append("import requests")
    lines.append("import os")
    lines.append("")
    lines.append("BACKEND_URL = os.environ.get('BACKEND_URL', 'http://localhost:8000')")
    lines.append("GPU_API_KEY = os.environ.get('GPU_API_KEY', 'mock-gpu-key')")
    lines.append("JOB_ID = os.environ.get('JOB_ID', 'mock-job-id')")
    lines.append("")
    # ponytail: 90s timeout — Render free tier spins down after 15min idle,
    # takes ~60s to wake up on first HTTP request. GPU callbacks must wait
    # for the backend to spin back up before the request can succeed.
    lines.append("BACKEND_TIMEOUT = int(os.environ.get('BACKEND_TIMEOUT', '90'))")
    lines.append("")
    lines.append("def notify_status(block, status):")
    lines.append("    try:")
    lines.append("        requests.post(f'{BACKEND_URL}/jobs/{JOB_ID}/status',")
    lines.append("            json={'block': block, 'status': status},")
    lines.append("            headers={'Authorization': f'Bearer {GPU_API_KEY}'}, timeout=BACKEND_TIMEOUT)")
    lines.append("    except Exception: pass")
    lines.append("")
    lines.append("def notify_output(block, output):")
    lines.append("    try:")
    lines.append("        requests.post(f'{BACKEND_URL}/jobs/{JOB_ID}/output',")
    lines.append("            json={'block': block, 'output': str(output)[:10000]},")
    lines.append("            headers={'Authorization': f'Bearer {GPU_API_KEY}'}, timeout=BACKEND_TIMEOUT)")
    lines.append("    except Exception: pass")
    lines.append("")
    lines.append("def notify_error(block, error):")
    lines.append("    try:")
    lines.append("        requests.post(f'{BACKEND_URL}/jobs/{JOB_ID}/error',")
    lines.append("            json={'block': block, 'error': str(error)},")
    lines.append("            headers={'Authorization': f'Bearer {GPU_API_KEY}'}, timeout=BACKEND_TIMEOUT)")
    lines.append("    except Exception: pass")
    lines.append("")

    seen = set()
    for node in nodes:
        if node.type in seen:
            continue
        seen.add(node.type)
        source = _source_for(node.type)
        if source:
            lines.append(f"# === {node.type} ===")
            lines.append(source.strip())
            lines.append("")

    lines.append("def main():")
    lines.append("    try:")

    order = _topological_sort(nodes, edges)
    if len(order) != len(nodes):
        raise ValueError("Cycle detected in pipeline graph")

    output_counter = 0
    output_map: dict = {}

    for node_id in order:
        node = next(n for n in nodes if n.id == node_id)
        block = BLOCK_REGISTRY.get(node.type)
        if not block:
            continue

        cleaned_params = {k: v for k, v in node.params.items() if not k.startswith("_")}
        params = ", ".join(f"{k}={v!r}" for k, v in cleaned_params.items())

        PORT_TO_PARAM = {"in": "in_1", "input": "in_1", "x": "in_1", "in_1": "in_1"}

        resolved_inputs = []
        for edge in edges:
            if edge.target == node_id:
                key = (edge.source, edge.source_port)
                if key in output_map:
                    var_name = f"out_{output_map[key]}"
                elif edge.source in output_map:
                    var_name = f"out_{output_map[edge.source]}"
                else:
                    var_name = f"out_{edge.source}"
                target_param = PORT_TO_PARAM.get(edge.target_port, edge.target_port)
                resolved_inputs.append(f"{target_param}={var_name}")
        inputs = ", ".join(resolved_inputs)

        args = ", ".join(filter(None, [inputs, params]))
        lines.append(f"        notify_status('{node.type}', 'running')")
        if len(block.outputs) <= 1:
            output_counter += 1
            output_map[node_id] = output_counter
            lines.append(f"        out_{output_counter} = {node.type}({args})")
            lines.append(f"        notify_output('{node.type}', out_{output_counter})")
        else:
            targets = []
            for o in block.outputs:
                output_counter += 1
                output_map[(node_id, o['name'])] = output_counter
                targets.append(f"out_{output_counter}")
            lines.append(f"        {', '.join(targets)} = {node.type}({args})")
            lines.append(f"        notify_output('{node.type}', {', '.join(targets)})")
        lines.append(f"        notify_status('{node.type}', 'done')")
    lines.append("        notify_status('pipeline', 'done')")
    lines.append("    except Exception as e:")
    lines.append("        notify_error('pipeline', e)")
    lines.append("        raise")
    lines.append("")
    lines.append('if __name__ == "__main__":')
    lines.append("    main()")
    return "\n".join(lines)


class CodeGenerator:
    def __init__(self, graph):
        self.graph = graph

    def generate(self) -> str:
        nodes = []
        for n in self.graph.nodes.values():
            nodes.append(PipelineNode(id=n.id, type=n.type, params=n.params))

        edges = []
        for e in self.graph.edges:
            edges.append(PipelineEdge(
                source=e.source,
                source_port=e.source_port,
                target=e.target,
                target_port=e.target_port
            ))

        return generate_code(nodes, edges)
