/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CoursRouteImport } from './routes/cours'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as CoursSlugRouteImport } from './routes/cours.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursRoute = CoursRouteImport.update({
  id: '/cours',
  path: '/cours',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursSlugRoute = CoursSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CoursRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cours': typeof CoursRouteWithChildren
  '/editor': typeof EditorRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/projets': typeof ProjetsRoute
  '/register': typeof RegisterRoute
  '/cours/$slug': typeof CoursSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cours': typeof CoursRouteWithChildren
  '/editor': typeof EditorRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/projets': typeof ProjetsRoute
  '/register': typeof RegisterRoute
  '/cours/$slug': typeof CoursSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cours': typeof CoursRouteWithChildren
  '/editor': typeof EditorRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/projets': typeof ProjetsRoute
  '/register': typeof RegisterRoute
  '/cours/$slug': typeof CoursSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cours'
    | '/editor'
    | '/how-it-works'
    | '/login'
    | '/projets'
    | '/register'
    | '/cours/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cours'
    | '/editor'
    | '/how-it-works'
    | '/login'
    | '/projets'
    | '/register'
    | '/cours/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cours'
    | '/editor'
    | '/how-it-works'
    | '/login'
    | '/projets'
    | '/register'
    | '/cours/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoursRoute: typeof CoursRouteWithChildren
  EditorRoute: typeof EditorRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  ProjetsRoute: typeof ProjetsRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours': {
      id: '/cours'
      path: '/cours'
      fullPath: '/cours'
      preLoaderRoute: typeof CoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cours/$slug': {
      id: '/cours/$slug'
      path: '/$slug'
      fullPath: '/cours/$slug'
      preLoaderRoute: typeof CoursSlugRouteImport
      parentRoute: typeof CoursRoute
    }
  }
}

interface CoursRouteChildren {
  CoursSlugRoute: typeof CoursSlugRoute
}

const CoursRouteChildren: CoursRouteChildren = {
  CoursSlugRoute: CoursSlugRoute,
}

const CoursRouteWithChildren = CoursRoute._addFileChildren(CoursRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoursRoute: CoursRouteWithChildren,
  EditorRoute: EditorRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  ProjetsRoute: ProjetsRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
