#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

ENV_FILE="${ENV_FILE:-.env.coolify}"
TOTAL_STAGES=7

banner "MLBlock Coolify setup"

# ── Stage 1: VPS coordinates ───────────────────────────────────────────────
stage "VPS: reachability"
say "We pin the VPS address and repo URL everything else derives from (sslip.io domains)."
ask VPS_IP "VPS public IP (ssh oracle-arm uses this):"
ask REPO_URL "Git repo URL Coolify will pull (https://github.com/...):"
open_url "http://$VPS_IP:8000"
step "Log in to the Coolify dashboard at the opened URL (create the admin account on first run)."
step "In another terminal, confirm SSH works: ssh ubuntu@$VPS_IP (or: ssh oracle-arm)."
pause "Press Enter once the dashboard loads and SSH works"
write_env VPS_IP "$VPS_IP"
write_env REPO_URL "$REPO_URL"

# ── Stage 2: Oracle firewall (authoritative: docs/coolify/firewall.md) ──────
stage "Oracle Cloud: firewall"
say "OCI console -> Networking -> Virtual Cloud Networks -> VCN -> Security Lists -> Ingress Rules."
say "Authoritative list is docs/coolify/firewall.md (note: it adds 6001/6002, which the old guide omits)."
step "Add Ingress 0.0.0.0/0 TCP ports 22 (SSH), 80 + 443 (Traefik), 6001 + 6002 (Coolify realtime), 8000 (dashboard)."
step "Keep the ICMP rules (3,4) and the 10.0.0.0/16 internal full-traffic rule from firewall.md."
pause "Press Enter once the ingress list matches firewall.md"
step "On the host (ssh), open the same ports in iptables/ufw if enabled, and add a 4G swapfile for ARM builds (see docs/coolify/coolify-deployment.md section 2)."
pause "Press Enter once host firewall + swap are done"

# ── Stage 3: Coolify project, resource, domains ─────────────────────────────
stage "Coolify: project + sslip domains"
say "Dashboard -> Projects -> + Add (name MLBlock, environment production)."
step "+ New Resource -> Git Repository -> paste REPO_URL, branch main, Build Pack Docker Compose, compose location docker-compose.coolify.yml."
note "Coolify relabels these screens often; if a label differs, tell me and I update this script."
pause "Press Enter once the resource is created and the compose file is detected"
say "Per-service Domains (Coolify discovers backend + frontend from the compose file):"
step "frontend service -> Domains: http://frontend.$VPS_IP.sslip.io"
step "backend service -> Domains: http://backend.$VPS_IP.sslip.io (no :8000 suffix; the proxy handles routing)."
ask FRONTEND_DOMAIN "Frontend domain (Enter keeps current):"
ask BACKEND_DOMAIN "Backend domain (Enter keeps current):"
write_env FRONTEND_DOMAIN "$FRONTEND_DOMAIN"
write_env BACKEND_DOMAIN "$BACKEND_DOMAIN"
pause "Press Enter once both domains are saved in Coolify"

# ── Stage 4: Supabase values ────────────────────────────────────────────────
stage "Supabase: project values"
say "Supabase Dashboard -> your project -> Project Settings -> Data API (URL + keys) -> Database (pooler connection)."
open_url "https://supabase.com/dashboard"
step "Copy the Project URL and the publishable key."
ask SUPABASE_URL "Paste SUPABASE_URL (https://[ref].supabase.co):"
ask SUPABASE_PUBLISHABLE_KEY "Paste SUPABASE_PUBLISHABLE_KEY (sb_publishable_...):"
step "Reveal + copy the service_role / secret key."
ask_secret SUPABASE_SECRET_KEY "Paste SUPABASE_SECRET_KEY:"
step "Copy the JWT Secret (Settings -> Data API -> JWT Settings)."
ask_secret SUPABASE_JWT_SECRET "Paste SUPABASE_JWT_SECRET:"
step "Database -> Connect -> pooler (transaction mode, port 6543) connection string as postgres.[ref], percent-encoding ? @ * in the password."
ask_secret DATABASE_URL "Paste DATABASE_URL (port 6543, percent-encoded):"
write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_PUBLISHABLE_KEY "$SUPABASE_PUBLISHABLE_KEY"
write_env SUPABASE_SECRET_KEY "$SUPABASE_SECRET_KEY"
SUPABASE_JWKS_URL="${SUPABASE_URL%/}/auth/v1/.well-known/jwks.json"
write_env SUPABASE_JWKS_URL "$SUPABASE_JWKS_URL"
write_env SUPABASE_JWT_SECRET "$SUPABASE_JWT_SECRET"
write_env DATABASE_URL "$DATABASE_URL"

# ── Stage 5: runtime values + paste into Coolify ────────────────────────────
stage "Runtime: Vast + GPU callback"
open_url "https://cloud.vast.ai"
step "Vast.ai console -> Account -> API key -> copy."
ask_secret VAST_API_KEY "Paste VAST_API_KEY:"
ask MLBLOCK_RUN_MODE "MLBLOCK_RUN_MODE (gpu for prod, local for testing):"
step "Generate a 32+ char shared secret for GPU->backend callbacks (or paste your own)."
ask_secret GPU_API_KEY "Paste GPU_API_KEY (empty = generate one):"
[[ -n "${GPU_API_KEY:-}" ]] || GPU_API_KEY="$(python3 -c 'import uuid; print(uuid.uuid4())')"
ask BACKEND_URL "Public backend URL (https://... or http://backend.<ip>.sslip.io):"
ask CORS_ORIGINS "Allowed frontend origin(s), comma-separated:"
write_env VAST_API_KEY "$VAST_API_KEY"
write_env MLBLOCK_RUN_MODE "$MLBLOCK_RUN_MODE"
write_env GPU_API_KEY "$GPU_API_KEY"
write_env BACKEND_URL "$BACKEND_URL"
write_env CORS_ORIGINS "$CORS_ORIGINS"
say "Now paste EVERYTHING from .env.coolify into Coolify -> resource -> Environment Variables."
warn "VITE_* keys must be marked Available at Build Time: they bake into the frontend bundle."
pause "Press Enter once Coolify holds all variables"

# ── Stage 6: frontend build args ────────────────────────────────────────────
stage "Frontend: build args"
say "These bake into the bundle at build time, so they must be set in Coolify before (re)deploy."
ask VITE_API_BASE_URL "VITE_API_BASE_URL (public backend URL):"
ask VITE_SUPABASE_URL "VITE_SUPABASE_URL (same as SUPABASE_URL):"
ask VITE_SUPABASE_PUBLISHABLE_KEY "VITE_SUPABASE_PUBLISHABLE_KEY:"
ask SITE_URL "SITE_URL (public frontend URL):"
write_env VITE_API_BASE_URL "$VITE_API_BASE_URL"
write_env VITE_SUPABASE_URL "$VITE_SUPABASE_URL"
write_env VITE_SUPABASE_PUBLISHABLE_KEY "$VITE_SUPABASE_PUBLISHABLE_KEY"
write_env SITE_URL "$SITE_URL"
pause "Press Enter once these four are also in Coolify env vars"

# ── Stage 7: push-to-main redeploy ──────────────────────────────────────────
stage "CI: deploy webhook"
say "Coolify resource -> Webhooks (or Deployments -> Webhooks) -> copy the Deploy Webhook URL."
step "Profile -> Keys & Tokens -> API Tokens -> create one with deployment permissions."
ask_secret COOLIFY_WEBHOOK_URL "Paste the Deploy Webhook URL:"
ask_secret COOLIFY_API_TOKEN "Paste the Coolify API token (empty if your webhook needs none):"
set_secret COOLIFY_WEBHOOK_URL "$COOLIFY_WEBHOOK_URL"
if [[ -n "${COOLIFY_API_TOKEN:-}" ]]; then set_secret COOLIFY_API_TOKEN "$COOLIFY_API_TOKEN"; fi
note "These match secrets.COOLIFY_WEBHOOK_URL / secrets.COOLIFY_API_TOKEN in .github/workflows/deploy-coolify.yml."
say "Verify: push to main (or workflow_dispatch), watch Coolify build both images, then:"
say "  curl -f $BACKEND_URL/healthz   # expect {\"status\":\"ok\",\"run_mode\":\"gpu\"}"
pause "Press Enter once a deploy is green and /healthz answers"
# ──────────────────────────────────────────────────────────────────────────

finish
